### ISSUE TITLE
In readme you mentioned one feature two times.

### ISSUE THREAD

**Issue by maruthu001** [fssa-batch3/thamim.subansait__web_project#13]
### Description of issue
In song CRUD (as buyer): you put one feature two times.

```
Path:      /pages/homepage/buyer%20homepage.html
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--doboo.netlify.app%2Fpages%2Fhomepage%2Fbuyer%2520homepage.html&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--doboo.netlify.app/pages/homepage/buyer%20homepage.html)

**Comment by Thamimtommy** [comment]
finished the issue. please check it now. Thank you.
